INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Rosa Nilma Dos Santos Ramos Cruz', 'rosanilma89@gmail.com', '79996015387', 'Confirmo minha presença em seu casamento ', 'Família', '2024-10-06 20:30:10', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Paulo Rocha Cruz', '-', '79999217775', NULL, 'Família', '2024-11-04 21:32:43', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Paula Rocha Dos Santos Ramos', 'paullarochaster@gmail.com', '47991362662', 'Desejo a vcs uma união duradoura, que possam construir um lar repleto de paz e amor onde vcs também construíram uma família, que possam prosperar e estarem um ao lado do outro sempre, para fortalecer o que veem de bom no outro. Estarei torcendo pela felicidade dessa família sempre! Vamos festejar muito o nascimento dessa nova fase em suas vidas!', 'Família', '2024-10-16 06:29:23', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Pablo Rocha', 'pablorochaa0303@gmail.com', '79999043647', NULL, 'Família', '2024-10-09 09:42:50', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Kelyanne Rocha Dos Santos Ramos', 'kelzynnharamos@gmail.com', '799996592626', 'Que sejam felizes amo vcs espero q me dê logo sobrinho kkkkk', 'Família', '2024-10-06 20:47:32', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Alany Grabriely', '-', '79 9937-3509', NULL, 'Família', '2024-11-04 21:32:43', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Sérgio Bomfim', 'melosergio16@gmail.com', '79999180721', 'Toda felicidade do mundo ainda é pouco pra vocês ', 'Família', '2024-10-07 05:43:55', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Sineide Maria', 'oliveiraneide135@gmail.com', '79999293977', NULL, 'Família', '2024-11-04 21:07:05', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Thamyres Oliveira Bomfim', 'bomfimthamyres@gmail.com', '79999700490', 'Ansiosa para esse dia especial ❤️ amo vocês.', 'Família', '2024-11-04 22:03:12', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Lucas Gabriel', 'oliveiraneide135@gmail.com', '79999293977', NULL, 'Família', '2024-11-04 21:07:05', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('José Tomaz Bastos Souza Neto', 'eng.tomazneto@gmail.com', '79999528723', NULL, 'Família', '2024-10-31 11:08:22', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Roberta Bomfim', 'robertabomfims@hormail.com', '79999998723', 'Que sejam muito  felizes com a linda família que construirão.
Que a cumplicidade prevaleça quando um precisar apoiar o outro
Que mesmo nos momentos difíceis nunca falte o diálogo……QUE SEJAM FELIZES PARA SEMPRE!!!', 'Família', '2024-10-06 22:14:28', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Letícia Tavares Nunes Da Silva', 'leticiatavars1010@gmail.com', '79996433843', NULL, 'Família', '2024-10-31 11:07:38', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Maysa Pinto', 'maysampinto@hotmail.com', '79998360505', 'Amo vcssss e estou muito feliz de fazer parte desse momento tão lindo e especial. Muito obrigada 🤍🤍🤍', 'Padrinhos', '2024-10-07 06:33:37', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Lorhany', 'lorhanymoraes@yahoo.com.br', '79999787516', 'Ansiosa para presenciar essa casamento incrível 🖤', 'Padrinhos', '2024-11-04 21:13:20', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Mariana Rocha Barreto', 'maare-r@hotmail.com', '79991990654', 'Eu já estou literalmente com a roupa de ir pronta no guarda roupa!!! 
Mais uma vez, obrigada pelo convite para participar desse momento especial como madrinha de vcs! Fico mto feliz!! <3 <3 <3 ', 'Padrinhos', '2024-10-09 15:55:02', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Vitória Lima', 'vitorialimac@gmail.com', '79998450331', NULL, 'Padrinhos', '2024-10-07 12:30:06', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Mariana Mendonça', 'mari_mendonca_araujo@hotmail.com', '79999391997', 'Meus amores, desejo que o dia de vocês seja incrível! 
Vocês merecem viver tudo de melhor que há neste mundo. Eu torço demais pela felicidade e sucesso de ambos. 
Saibam que podem contar sempre comigo.
Thais, amiga-irmã, nem acredito que este grande dia está chegando. Estarei lá super emocionada vendo você crescer e indo para uma nova etapa de sua vida.
Tony, parceirinho que minha best me deu, cuide muito bem dela!!!! Feliz demais pela escolha de minha amiga, acertou em cheio. Você é um cara íntegro, gente boa e não mede esforços para fazê-la feliz. 

Amo vocês 🥹❤️', 'Padrinhos', '2024-11-04 21:12:53', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Joseane', NULL, NULL, NULL, 'Padrinhos', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Jess Moreira Caetano', 'jessicamcaetano@gmail.com', '31995135993', NULL, 'Padrinhos', '2024-11-04 21:08:33', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Mariana Perígolo Ferreira', 'marianaperigolof@gmail.com', '31975246343', 'Eu amo vocês demais 💖 estarei aqui para tudo, mesmo com a distância, me farei presente e espero poder cumprir meu papel de madrinha com muito amor e cuidado. Felicidade define o que estou sentindo e não vejo a hora de comemorar esse momento tão incrível juntinha com vocês. ', 'Padrinhos', '2024-10-07 10:06:22', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Maria Helena Pimentel', 'pimentel.mhelena@gmail.com', '81997833496', 'Lindos, divos! Tô ANSIOSAAAAAAAAAA', 'Padrinhos', '2024-11-05 08:48:30', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Amanda', 'amanda.mcosta02@gmail.com', '75991593696', 'Que a união de vocês seja sempre fonte de muito amor, respeito e parceira. Desejo muitos e muitos anos juntos!!!! Amo vocês! ', 'Padrinhos', '2024-10-07 23:19:24', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Lucas Roberto', 'lucas.roberto@icloud.com', '79991801994', NULL, 'Padrinhos', '2024-11-05 17:35:49', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Fagner Souza', 'flssouza@me.com', '79991271541', 'Eu amo vcs e to feliz demais', 'Padrinhos', '2024-11-05 12:09:31', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Kauê Lucas Nunes Santana', 'psikaue@gmail.com', '79998156684', NULL, 'Padrinhos', '2024-11-05 17:24:41', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Victor Prudente', 'victorprudente.10@gmail.com', '31971839950', NULL, 'Padrinhos', '2024-10-06 20:56:41', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Charlys', NULL, NULL, NULL, 'Padrinhos', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Kevinn Anthony Calazans De Oliveira', 'kevinncalazans@gmail.com', '79996842420', 'Acho que já cansei de dizer o quanto admiro cada um de vocês dois de forma individual, como pessoas e profissionais, mas nunca disse o quanto admiro o relacionamento que vocês construiram ao longo desses anos. É lindo de ver o quanto um apoia o outro, como são tão companheiros e como buscam crescer juntos na vida. Que Deus continnue abençoado esse casal e que esse novo ciclo venha para renovar ainda mais esse relacionamento lindo! To muito feliz por vocêêês!! Amo vocês!! Beijão!! <3', 'Padrinhos', '2024-10-15 21:47:20', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Gabriel Tavares', 'gabrieltavaresdireito1991@gmail.com', '79999220603', NULL, 'Padrinhos', '2024-11-05 17:28:51', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Abdala Power Santana De Souza', 'abdalapower.pw@gmail.com', '79991064689', 'Estou muito feliz por vocês pois acompanhei desde o início quando morava eu e Tony no mesmo apartamento, foram épocas difíceis mas foi top o tempo que durou, só sabe quem morava lá. Espero que você meu brother Tony e você Thaís sejam felizes para todo sempre, nada melhor do que encontrar uma pessoa boa na vida que nos faça bem e esteja ao nosso lado nos momentos bons ou ruins.
Podem contar comigo para o que der e vier.
Um abraço do seu amigo, parceiro e agora padrinho de vocês. Amo muito vocês dois, estão aqui no meu coração. ', 'Padrinhos', '2024-11-05 23:32:23', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Thiago', NULL, NULL, NULL, 'Padrinhos', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Nathan Feitoza', 'nathanfeitoza@outlook.com.br', '79996474507', 'Muito feliz por esse momento tão especial para vocês!!!', 'Padrinhos', '2024-10-07 12:27:54', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Álvaro Gabriel Sampaio', 'alvarogabrieel@hotmail.com', '79999181521', 'Que felicidades compartilhar esse momento tão especial com vocês!!!  Que cada dia seja uma oportunidade de construir uma vida repleta de cumplicidade, carinho e conquistas, mais forte que a que vocês já tem.

Desejo que continuem sendo companheiros de todas as horas, sempre com sorrisos e abraços que confortam, e com sonhos que inspirem a caminhada de vocês.', 'Amigo', '2024-10-07 11:31:45', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Helem Pontes', 'helem_monique@hotmail.com', '79999777857', 'Que o amor de vocês cresça cada dia mais! Me inspiro muito no respeito de vocês como um casal, amo os dois💘 que sejam MUUUITO felizes por toda a eternidade e estou esperando que venham ser meus vizinhos em Buenos Aires ', 'Amigo', '2024-10-16 20:30:01', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Matías Danani', 'mdanani@fjsolutions.com.ar', '79999777857', 'Amigos! 

Qué lindo compartir este momento tan especial con ustedes. Les deseo lo mejor en esta nueva etapa, que todo sea como lo imaginaron.

Los quiero, Mati!', 'Amigo', '2024-10-16 20:33:35', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Igor Fonseca', 'igoreaf96@gmai.com', '81992498140', 'Ansioso para participar desta data especial e conhecer a cidade de vocês, lindos. Desejando muita felicidade nesta nova etapa! ', 'Amigo', '2024-11-05 11:47:24', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Arthur Matheus Macêdo Tavares', 'arthurmatheuus@gmail.com', '81983321632', 'Confirmado!', 'Amigo', '2024-11-05 11:42:00', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Mariana Veloso Passos', 'mareanaveloso@gmail.com', '79991033337', 'Achei muito chique e fofo isso aqui viu ', 'Cônjuge Amigo', '2024-10-06 20:31:04', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Thiago William Sa Goncalves', 'thiagowilliam.sg@gmail.com', '11912121986', 'Batatinha quando nasce se esparrama pelo chão, desejo tudo de bom, levo vocês no meu coração! <3

Amo vocês papais! Contem comigo pra tudo!', 'Amigo', '2024-10-06 22:01:15', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Maria Beatriz', 'mariabmdantas@gmail.com', '79998233532', 'Feliz demais por poder fazer parte desse momento tão especial na vida do casal! Espero Deus ilumine e abençoe a união de vcs pra sempre!! ♥️♥️♥️', 'Amigo', '2024-10-25 14:40:52', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Yuri Silveira', NULL, NULL, NULL, 'Cônjuge Amigo', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Luísa Moura', 'luisaccdemoura@hotmail.com', '79999874519', NULL, 'Amigo', '2024-11-02 22:01:43', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Marcos Torres', 'marcostorresbf@gmail.com', '79999630410', 'Parabéns a esse casal mais que querido, que Deus continue abençoando essa união! Muito feliz em poder celebrar esse amo de vocês.', 'Amigo', '2024-10-06 20:40:35', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Carolina Costa', 'c.costaesales@gmail.com', '79998388416', NULL, 'Amigo', '2024-10-06 21:02:37', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Mauricio Souza Dantas', 'soles369@yahoo.com.br', '79998365111', NULL, 'Amigo', '2024-10-28 12:19:46', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Rafael Lima Santos', 'rafael.lsantos03@gmail.com', '79999307033', 'Feliz em participar desse momento.

Felicidades ❤️', 'Amigo', '2024-10-11 20:19:46', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Lucas Barros Nascimento', 'lucbarnasc@gmail.com', ' 79 99923-8862', NULL, 'Cônjuge Amigo', '2024-11-04 21:32:43', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Juliana De Melo Rosa', 'julianadmrosa@gmail.com', '24981454790', NULL, 'Amigo', '2024-11-05 12:10:16', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Natalia Nonato', 'nnonato97@gmail.com', '79998177005', NULL, 'Amigo', '2024-11-05 12:47:10', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Caio Henrique Ferreira', 'caioferrs@gmail.com', '79999769659', NULL, 'Cônjuge Amigo', '2024-11-05 12:48:26', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Ana Carolina Menezes De Oliveira', 'menezes.anacarolinamo@gmail.com', '79999937873', 'Que Deus proporcione a vocês todo o amor do mundo, o mais acolhedor, respeitoso e mais gostoso 💙', 'Amigo', '2024-10-09 01:05:34', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Vinícius Meri Correia Piones', 'viniciuspiones@gmail.com', '79988633314', 'Feliz demais em participar desse momento lindo e ainda por cima fazer um som pra animar a galera hehe <3', 'Cônjuge Amigo', '2024-11-05 11:48:24', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Kayo Oliveira', 'kayojose@hotmail.com', '79998294154', 'Estou muito feliz por essa realização de vocês ! ', 'Amigo', '2024-10-06 21:21:11', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Leticia Ayala', 'Leticia.ayala15@hotmail.com', '79998987459', NULL, 'Amigo', '2024-10-06 21:43:06', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Josan Silva Dos Santos Junior', 'josanjr2001@hotmail.com', '79996475658', 'Queridos amigos,

Gostaria de deixar registrado o quanto estou grato por ter sido convidado a compartilhar um pouco mais da vida com vocês e em específico, esse momento tão especial. É uma alegria imensa estar ao lado de pessoas tão incríveis, que sempre emanam carinho e boas energias. Vocês são o tipo de casal que inspira todos ao redor, e fico muito feliz em fazer parte disso.

Desejo que a vida continue trazendo o melhor para vocês, porque não merecem nada menos. Que o amor, a felicidade e o sucesso acompanhem cada passo dessa jornada juntos.

Com todo meu carinho e gratidão.', 'Amigo', '2024-10-07 10:52:19', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Carlos Sousa', 'carlossousa.cs@gmail.com', '79998651933', 'Vocês acham mesmo que eu iria ficar de fora do evento do ano? NUNCA!!

Fico muito feliz por saber o quanto vocês são importantes um para o outro e por me encorajarem a enfatizar sempre que o amor é real. Vocês são como yin e yang, se complementam nas suas particularidades!

P.S.: Já estou chorando! E outra: eu e Josan estaremos na beca para enaltecê-los no dia mais importante das suas vidas!', 'Amigo', '2024-10-08 10:36:51', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Samuel De Santana', 'samuellrs10@gmail.com', '79999587164', 'Muito feliz em fazer parte desse momento lindo! Que vocês ultrapassem a esfera da felicidade!!!  ', 'Amigo', '2024-11-05 11:54:39', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Bruno Freire Barbosa', 'engfreire.bruno@gmail.com', '79996447654', NULL, 'Amigo', '2024-11-01 11:18:11', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Raissa', NULL, NULL, NULL, 'Amigo', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Roberto', NULL, NULL, NULL, 'Cônjuge Amigo', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('André Marinho', 'alsmarinho98@gmail.com', '82996940581', NULL, 'Amigo', '2024-10-06 20:45:50', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Mário Loureiro', 'mario_loureiro.dev@outlook.com', '(79) 99904-2873', 'Que o Senhor abençoe e ilumine esta união, enchendo-a de graça, amor e bênçãos abundantes.', 'Amigo', '2024-10-23 14:19:32', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Kawanny Menezes', 'mario_loureiro.dev@outlook.com', '(79) 99904-2873', 'Que o Senhor abençoe e ilumine esta união, enchendo-a de graça, amor e bênçãos abundantes.', 'Cônjuge Amigo', '2024-10-23 14:19:32', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Pedro Igor', NULL, NULL, NULL, 'Amigo', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Ítala Eduarda', NULL, NULL, NULL, 'Cônjuge Amigo', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('João Victor Dos Santos Costa', 'jv07_aju@hotmail.com', '79999933900', 'Boooooa Tony kkkkk parabéns aos noivos! Muitas felicidades e harmonia pra vocês!', 'Amigo', '2024-10-18 16:22:30', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Rubens Carvalho', 'hotrubens@hotmail.com', '79991009113', NULL, 'Amigo', '2024-11-05 19:11:53', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Lidiane', NULL, NULL, NULL, 'Cônjuge Amigo', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Ana Margarida Barreto', 'ampbarreto@icloud.com', '79988431088', 'Felicidades!!! ', 'Cônjuge Amigo', '2024-11-05 23:35:32', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Larissa Dias', 'larissa.santtos15@hotmail.com', '79991209422', NULL, 'Cônjuge Amigo', '2024-10-28 18:33:21', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Andressa', 'andressagabrielle45@gmail.com', '75999556685', 'Está chegando o grande dia e com certeza o frio na barriga e a ansiedade estão presentes ❤️
Mas sei que no meio dessa ansiedade, vocês sabem que a melhor decisão que vocês tomaram na vida foi exatamente essa: o casamento, que Deus permita que o amor de vocês se perpetue para sempre! #vemcasamento', 'Cônjuge Amigo', '2024-11-05 18:05:35', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Felipe Caetano', NULL, NULL, NULL, 'Amigo', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Gabriel (gab)', NULL, NULL, NULL, 'Amigo', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Fabio', NULL, NULL, NULL, 'Trabalho', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Elaine', NULL, NULL, NULL, 'Trabalho', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('John', NULL, NULL, NULL, 'Amigo', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Sandra Nascimento De Oliveira', 'sandrabonfim39@gmail.com', '79998346245', 'Que a felicidade reine em cada momento desta União, dos meus queridos sobrinhos !!!', 'Convidado Pais', '2024-10-09 12:42:48', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Helino Silva De Oliveira', 'helinoadv@gmail.com', '79999642069', 'Imensamente feliz por este momento. Que o Amor e a Felicidade estejam presentes em todos os momentos desta União!', 'Convidado Pais', '2024-10-09 12:40:19', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Guilherme Nascimento De Oliveira', 'glhrm.ndo@gmail.com', '79999164833', 'Desejo muita felicidade para os meus primos !!!', 'Convidado Pais', '2024-10-09 12:44:27', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Carlos Henrique Melo Passos', 'andersoncpassos@yahoo.com.br', '71988333878', NULL, 'Convidado Pais', '2024-10-25 19:15:44', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Eliane', NULL, NULL, NULL, 'Convidado Pais', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Tio Sergio', NULL, NULL, NULL, 'Convidado Pais', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Maria Cristina De Sousa Silva', 'mariacristinamcss466@gmail.com', '79999838761', 'Que essa união  seja fortalecida a cada dia, com amor,carinho e dedicação e atitudes de um para com o outros e que o nosso Deus os abençoe em nome de Jesus!', 'Convidado Pais', '2024-10-09 12:36:15', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Serginho', NULL, NULL, NULL, 'Convidado Pais', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Kaike', NULL, NULL, NULL, 'Convidado Pais', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Vitor', NULL, NULL, NULL, 'Convidado Pais', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Tia Kel', 'fm8745482@gmail.com', '79998893991', 'Felicidades para vocês, que o Senhor esteja presente em todos os momentos da vida dos dois. 
A tia ama muito e deseja tudo de melhor Sempre.', 'Convidado Pais', '2024-10-24 22:25:34', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Maria Auxiliadora Dos Santos', NULL, '79 9949-8375', NULL, 'Convidado Pais', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Linconl', NULL, NULL, NULL, 'Convidado Pais', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Michael Francis Silva Guimarães', 'michaelguiboy@gmail.com', '79998190846', 'Que Deus cubra de bençãos e felicidade o casamento de vocês!', 'Convidado Pais', '2024-10-09 12:21:32', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Maria Izabela', 'belanardone@outlook.com', '79999073487', 'O que Deus une na terra é ligado no céu! Deus abençoe vocês. ✨🙏🏽', 'Convidado Pais', '2024-10-09 12:25:29', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Valdir Pereira Barbosa E Juçara Barbosa', 'juandraus@uol.com.br', '79998643776', 'Que nessa nova caminhada vocês tenham uma vida repleta de amor, confiança e muitas realizações. ', 'Convidado Pais', '2024-10-30 19:14:35', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Jussara', NULL, NULL, NULL, 'Convidado Pais', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Ernesto', NULL, NULL, NULL, 'Convidado Pais', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Ângela Melo', 'angelampmelo@hotmail.com', '79999825115', NULL, 'Convidado Pais', '2024-10-09 20:43:28', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Luiz José', 'luizjapdemelo@gmail.com', '79999727294', NULL, 'Convidado Pais', '2024-10-12 12:18:54', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Berenice', 'luizjapdemelo@gmail.com', '79999727294', NULL, 'Convidado Pais', '2024-10-12 12:18:54', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Edson Passos', 'passosedson@hotmail.com', '(79)99890-4406', 'Desejo a vocês muitas felicidades e compreensão e que, sempre juntos, construam uma vida próspera e com muita paz.', 'Convidado Pais', '2024-10-13 08:56:49', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Rosa', NULL, NULL, NULL, 'Convidado Pais', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Marco Aurélio Regis Dantas', 'marco@rdantas.com.br', '7988194869', 'Mais uma vez, paz, amor, saúde, felicidade, vida longa. 
Coisas boas!!!!', 'Convidado Pais', '2024-10-10 22:13:33', NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Dinora', NULL, NULL, NULL, 'Convidado Pais', NULL, NULL);
INSERT INTO convidados ("Nome", "Email", "Telefone", "Mensagem", "TipoConvidado", "DataHoraConfirmacao", "DataHoraCheckIn") VALUES ('Isabele Inácio', 'isabele.inacio@hotmail.com', '79998120254', NULL, 'Amigo', '2024-11-05 16:54:04', NULL);